"""
Smart Expense Tracker API

Endpoints:
  POST   /expenses              -> add an expense
  GET    /expenses              -> list all expenses (optional ?category=)
  GET    /expenses/total        -> total expenses (optional ?category= for per-category total)
  GET    /expenses/total/overall -> overall total across all expenses
  DELETE /expenses/{expense_id} -> delete an expense

Interactive docs (bonus: OpenAPI/Swagger) are auto-generated by FastAPI at /docs.
"""
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import JSONResponse

from src.models import Expense, ExpenseCreate, TotalResponse
from src.storage import ExpenseStore

app = FastAPI(
    title="Smart Expense Tracker API",
    description="A small REST API to track personal expenses with totals, filtering, and Swagger documentation.",
    version="1.0.0",
    openapi_tags=[
        {"name": "expenses", "description": "Create, list, filter, total, and delete expenses."}
    ],
)

store = ExpenseStore()


@app.get("/", include_in_schema=True, tags=["general"], summary="Welcome")
def welcome() -> dict[str, str]:
    return {
        "message": "Smart Expense Tracker API is running",
        "docs": "http://127.0.0.1:8000/docs",
        "view_all_expenses": "http://127.0.0.1:8000/expenses",
    }


@app.post("/expenses", response_model=Expense, status_code=201, tags=["expenses"])
def add_expense(payload: ExpenseCreate) -> Expense:
    expense = Expense(**payload.model_dump())
    return store.add(expense)


@app.get(
    "/expenses",
    response_model=list[Expense],
    tags=["expenses"],
    summary="Filter expenses",
    description="Return stored expenses. Use the optional category query parameter to filter the results.",
)
def list_expenses(
    category: str | None = Query(
        default=None, description="Filter expenses by category (case-insensitive)"
    )
) -> list[Expense]:
    return store.list_all(category)


def _build_total_response(category: str | None) -> TotalResponse:
    total, count = store.total(category)
    return TotalResponse(total=total, category=category, count=count)


@app.get("/expenses/total", response_model=TotalResponse, tags=["expenses"])
def get_total(
    category: str | None = Query(
        default=None, description="If given, total is scoped to this category"
    )
) -> TotalResponse:
    """Return a total summary where total is the sum and count is the number of matching expenses."""
    return _build_total_response(category)


@app.get(
    "/expenses/total/overall",
    response_model=TotalResponse,
    summary="Get overall total",
    description="Returns a summary where total is the sum of all expenses and count is the number of matching expenses.",
    tags=["expenses"],
)
def get_overall_total() -> TotalResponse:
    """Return the total of all stored expenses, regardless of category."""
    return _build_total_response(None)


@app.delete("/expenses/{expense_id}", status_code=200, tags=["expenses"])
def delete_expense(expense_id: str) -> JSONResponse:
    deleted = store.delete(expense_id)
    if not deleted:
        raise HTTPException(status_code=404, detail=f"Expense '{expense_id}' not found")
    return JSONResponse(content={"deleted": expense_id})
